name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install NASM
        run: sudo apt-get update && sudo apt-get install -y nasm

      - name: Build each folder
        working-directory: ./lab1
        run: |
          cd ../lab1
          /usr/bin/nasm -g -f elf64 lab.s -o lab.o
          make
          cd ../lab2
          /usr/bin/nasm -g -f elf64 lab.s -o lab.o
          make
          cd ../lab3
          /usr/bin/nasm -g -f elf64 lab.s -o lab.o
          make

      - name: Create archive
        run: |
          zip -r build.zip lab1/lab lab2/lab lab3/lab
          
      - name: Upload archive
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: build.zip